/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface.h"
#include <time.h>

typedef enum {
	DATETIME,
	MERGE,
	REV_ECHO,
	LISTDIR,
	ADD_MAT,
	QUIT
} operation_t;

typedef struct {
	operation_t operation;
	char* list1[256];
	int list1_len;
	char* list2[256];
	int list2_len;
}command_t;

void parseStdIO(char* line, command_t* cmd){

	const char* date_command = "rdate";
	const char* merge_command = "rmerge";
	const char* echo_command = "recho";
	const char* rdir_command = "rdir";
	const char* addmat_command = "raddmat";
	const char* quit_command = "q";

	int i, j;


	if(!strncmp(line, date_command, 5)){
		//printf("you entered data command \n %s", line);
		cmd->operation = DATETIME;

	}
	else if(!strncmp(line, merge_command, 6)){

	}
	else if(!strncmp(line, echo_command, 5)){

	}
	else if(!strncmp(line, rdir_command, 4)){

	}
	else if(!strncmp(line, addmat_command, 7)){

		for(i=0; i<4; i++){
			cmd->list1[i] = "1";
			cmd->list2[i] = "25";
		}
		cmd->operation = ADD_MAT;
		cmd->list1_len = 4;
		cmd->list2_len = 4;
	}
	else if(!strncmp(line, quit_command, 1)){
		cmd->operation = QUIT;
	}
	else{

	}

}

void
interface_progs_1(char *host)
{
	CLIENT *clnt;
	dir_res  *result_1;
	directoryName_t  read_dir_1_arg;
	matrix_t  *result_2;
	matrix_t  add_matrix_1_arg;
	text_t  *result_3;
	text_t  reverse_echo_1_arg;
	dataSet_t  *result_4;
	dataSet_t  merge_list_1_arg;
	u_int  *result_5;
	char *get_time_1_arg;
	int i, j;

	command_t cmd;
	char line[1024];

#ifndef	DEBUG
	clnt = clnt_create (host, INTERFACE_PROGS, DIR_PROG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	while(1){
		printf("RPC> ");
		while(fgets(line, sizeof(line), stdin) != NULL){
			parseStdIO(line, &cmd);
			switch(cmd.operation){
			case DATETIME:
				result_5 = get_time_1((void*)&get_time_1_arg, clnt);
				if (result_5 == (u_int *) NULL) {
					clnt_perror (clnt, "call failed 1");
				}
				printf("Time on server: %s \n", ctime((time_t*)result_5));
				break;
			case MERGE:
				for(i=0; i<cmd.list1_len; i++){
					merge_list_1_arg.elements[i] = cmd.list1[i];
				}
				merge_list_1_arg.first_len = i+1;
				for(i=0; i<cmd.list2_len; i++){
					merge_list_1_arg.elements[i] = cmd.list2[i];
				}
				merge_list_1_arg.second_len = i+1;
				merge_list_1_arg.num_of_sets = 2;

				result_4 = merge_list_1(&merge_list_1_arg, clnt);
				if (result_4 == (dataSet_t *) NULL) {
					clnt_perror (clnt, "call failed 2");
				}
				break;
			case REV_ECHO:
				/*for(i=0; i<cmd.list1_len; i++){
					reverse_echo_1_arg.elements[i] = cmd.list1[i];
				}*/
				reverse_echo_1_arg.elements = cmd.list1[0];
				reverse_echo_1_arg.num_of_chars = cmd.list1_len;

				result_3 = reverse_echo_1(&reverse_echo_1_arg, clnt);
				if (result_3 == (text_t *) NULL) {
					clnt_perror (clnt, "call failed 3");
				}
				break;
			case LISTDIR:
				result_1 = read_dir_1(&read_dir_1_arg, clnt);
				if (result_1 == (dir_res *) NULL) {
					clnt_perror (clnt, "call failed 4");
				}
				break;
			case ADD_MAT:
				for(i=0; i<cmd.list1_len; i++){
					add_matrix_1_arg.elements[i] = atoi(cmd.list1[i]);
					//printf("mat A[%i] = %i \n ", i, add_matrix_1_arg.elements[i]);
				}
				add_matrix_1_arg.m = 2;
				for(i=0; i<cmd.list2_len; i++){
					add_matrix_1_arg.elements[4+i] = atoi(cmd.list2[i]);
					//printf("mat B[%i] = %i \n ", i, add_matrix_1_arg.elements[4+i]);
				}
				add_matrix_1_arg.n = 2;
				add_matrix_1_arg.num_of_matrices = 2;

				result_2 = add_matrix_1(&add_matrix_1_arg, clnt);
				if (result_2 == (matrix_t *) NULL) {
					clnt_perror (clnt, "call failed 5");
				};
				printf("Sum of matrices: \n");
				for(i=0; i< result_2->m; i++){
					for(j=0; j< result_2->n; j++){
						printf("%i ",result_2->elements[i*result_2->n + j]);
					}
					printf("\n");					
				}
				printf("\n");
				break;
			case QUIT:
				return;
			default:
				break;
			}
			cmd.operation = 99; // reset command
			break;
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	interface_progs_1 (host);
exit (0);
}
