/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface.h"


void
interface_progs_1(char *host)
{
	CLIENT *clnt;
	dir_res  *result_1;
	directoryName_t  read_dir_1_arg;
	matrix_t  *result_2;
	matrix_t  add_matrix_1_arg;
	text_t  *result_3;
	text_t  reverse_echo_1_arg;
	dataSet_t  *result_4;
	dataSet_t  merge_list_1_arg;
	u_int  *result_5;
	char *get_time_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INTERFACE_PROGS, DIR_PROG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = read_dir_1(&read_dir_1_arg, clnt);
	if (result_1 == (dir_res *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = add_matrix_1(&add_matrix_1_arg, clnt);
	if (result_2 == (matrix_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = reverse_echo_1(&reverse_echo_1_arg, clnt);
	if (result_3 == (text_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = merge_list_1(&merge_list_1_arg, clnt);
	if (result_4 == (dataSet_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = get_time_1((void*)&get_time_1_arg, clnt);
	if (result_5 == (u_int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	interface_progs_1 (host);
exit (0);
}
