/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface.h"

typedef enum {
	DATETIME,
	MERGE,
	REV_ECHO,
	LISTDIR,
	ADD_MAT
} operation_t;

typedef struct {
	operation_t operation;
	char* list1[256];
	int list1_len;
	char* list2[256];
	int list2_len;
}command_t;

void parseStdIO(char* line, command_t* cmd){

}

void
interface_progs_1(char *host)
{
	CLIENT *clnt;
	dir_res  *result_1;
	directoryName_t  read_dir_1_arg;
	matrix_t  *result_2;
	matrix_t  add_matrix_1_arg;
	text_t  *result_3;
	text_t  reverse_echo_1_arg;
	dataSet_t  *result_4;
	dataSet_t  merge_list_1_arg;
	u_int  *result_5;
	char *get_time_1_arg;
	int i, j;

	command_t cmd;
	char line[1024];

#ifndef	DEBUG
	clnt = clnt_create (host, INTERFACE_PROGS, DIR_PROG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	while(1){
		printf("RPC> ");
		while(fgets(line, sizeof(line), stdin) != NULL){
			parseStdIO(line, &cmd);
			switch(cmd.operation){
			case DATETIME:
				result_5 = get_time_1((void*)&get_time_1_arg, clnt);
				if (result_5 == (u_int *) NULL) {
					clnt_perror (clnt, "call failed 1");
				}
				break;
			case MERGE:
				for(i=0; i<cmd.list1_len; i++){
					merge_list_1_arg.elements[i] = cmd.list1[i];
				}
				merge_list_1_arg.first_len = i+1;
				for(i=0; i<cmd.list2_len; i++){
					merge_list_1_arg.elements[i] = cmd.list2[i];
				}
				merge_list_1_arg.second_len = i+1;
				merge_list_1_arg.num_of_sets = 2;

				result_4 = merge_list_1(&merge_list_1_arg, clnt);
				if (result_4 == (dataSet_t *) NULL) {
					clnt_perror (clnt, "call failed 2");
				}
				break;
			case REV_ECHO:
				for(i=0; i<cmd.list1_len; i++){
					reverse_echo_1_arg.elements[i] = cmd.list1[i];
				}
				reverse_echo_1_arg.num_of_chars = cmd.list1_len;

				result_3 = reverse_echo_1(&reverse_echo_1_arg, clnt);
				if (result_3 == (text_t *) NULL) {
					clnt_perror (clnt, "call failed 3");
				}
				break;
			case LISTDIR:
				result_1 = read_dir_1(&read_dir_1_arg, clnt);
				if (result_1 == (dir_res *) NULL) {
					clnt_perror (clnt, "call failed 4");
				}
				break;
			case ADD_MAT:
				for(i=0; i<cmd.list1_len; i++){
					add_matrix_1_arg.elements[i] = cmd.list1[i];
				}
				add_matrix_1_arg.m = i+1;
				for(i=0; i<cmd.list2_len; i++){
					add_matrix_1_arg.elements[i] = cmd.list2[i];
				}
				add_matrix_1_arg.n = i+1;
				add_matrix_1_arg.num_of_matrices = 2;

				result_2 = add_matrix_1(&add_matrix_1_arg, clnt);
				if (result_2 == (matrix_t *) NULL) {
					clnt_perror (clnt, "call failed 5");
				};
				break;
			default:
				break;
			}
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	interface_progs_1 (host);
exit (0);
}
