/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "interface.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

dir_res *
read_dir_1(directoryName_t *argp, CLIENT *clnt)
{
	static dir_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, READ_DIR,
		(xdrproc_t) xdr_directoryName_t, (caddr_t) argp,
		(xdrproc_t) xdr_dir_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matrix_t *
add_matrix_1(matrix_t *argp, CLIENT *clnt)
{
	static matrix_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD_MATRIX,
		(xdrproc_t) xdr_matrix_t, (caddr_t) argp,
		(xdrproc_t) xdr_matrix_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

text_t *
reverse_echo_1(text_t *argp, CLIENT *clnt)
{
	static text_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REVERSE_ECHO,
		(xdrproc_t) xdr_text_t, (caddr_t) argp,
		(xdrproc_t) xdr_text_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

dataSet_t *
merge_list_1(dataSet_t *argp, CLIENT *clnt)
{
	static dataSet_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MERGE_LIST,
		(xdrproc_t) xdr_dataSet_t, (caddr_t) argp,
		(xdrproc_t) xdr_dataSet_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

u_int *
get_time_1(void *argp, CLIENT *clnt)
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_TIME,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_u_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
