/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface.h"

dir_res *
read_dir_1_svc(directoryName_t *argp, struct svc_req *rqstp)
{
	static dir_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}

matrix_t *
add_matrix_1_svc(matrix_t *argp, struct svc_req *rqstp)
{
	static matrix_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

text_t *
reverse_echo_1_svc(text_t *argp, struct svc_req *rqstp)
{
	static text_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dataSet_t *
merge_list_1_svc(dataSet_t *argp, struct svc_req *rqstp)
{
	static dataSet_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

u_int *
get_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static u_int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
