/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface.h"

dir_res *
read_dir_1_svc(directoryName_t *argp, struct svc_req *rqstp)
{
	static dir_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}

matrix_t *
add_matrix_1_svc(matrix_t *argp, struct svc_req *rqstp)
{
	static matrix_t  result;

	/*
	 * insert server code here
	 */
	int m = argp->m;
	int n = argp->n;

	int i, j;

	int A[m*n];
	int B[m*n];
	int C[m*n];

	memcpy(A, argp->mat_elements, sizeof(int)*m*n);
	memcpy(B, (argp->mat_elements + m*n), sizeof(int)*m*n);

	for(i=0; i< m; i++){
		for(j=0; j<n; j++){
			/*for(k=0; k<p; k++){
				C[i*n+j] = A[i*n+k] + B[k*n+j];
			}*/
			C[i*n+j] = A[i*n+j] + B[i*n+j];
		}
	}

	memcpy(result.mat_elements, C, sizeof(int)*m*n);

	return &result;
}

text_t *
reverse_echo_1_svc(text_t *argp, struct svc_req *rqstp)
{
	static text_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dataSet_t *
merge_list_1_svc(dataSet_t *argp, struct svc_req *rqstp)
{
	static dataSet_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

u_int *
get_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static u_int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
