/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
interface_progs_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		directoryName_t read_dir_1_arg;
		matrix_t add_matrix_1_arg;
		text_t reverse_echo_1_arg;
		dataSet_t merge_list_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case READ_DIR:
		_xdr_argument = (xdrproc_t) xdr_directoryName_t;
		_xdr_result = (xdrproc_t) xdr_dir_res;
		local = (char *(*)(char *, struct svc_req *)) read_dir_1_svc;
		break;

	case ADD_MATRIX:
		_xdr_argument = (xdrproc_t) xdr_matrix_t;
		_xdr_result = (xdrproc_t) xdr_matrix_t;
		local = (char *(*)(char *, struct svc_req *)) add_matrix_1_svc;
		break;

	case REVERSE_ECHO:
		_xdr_argument = (xdrproc_t) xdr_text_t;
		_xdr_result = (xdrproc_t) xdr_text_t;
		local = (char *(*)(char *, struct svc_req *)) reverse_echo_1_svc;
		break;

	case MERGE_LIST:
		_xdr_argument = (xdrproc_t) xdr_dataSet_t;
		_xdr_result = (xdrproc_t) xdr_dataSet_t;
		local = (char *(*)(char *, struct svc_req *)) merge_list_1_svc;
		break;

	case GET_TIME:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_u_int;
		local = (char *(*)(char *, struct svc_req *)) get_time_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (INTERFACE_PROGS, DIR_PROG_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, INTERFACE_PROGS, DIR_PROG_VERS, interface_progs_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (INTERFACE_PROGS, DIR_PROG_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, INTERFACE_PROGS, DIR_PROG_VERS, interface_progs_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (INTERFACE_PROGS, DIR_PROG_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
